# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-26 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField(unique=True)),
                ('coursename', models.CharField(max_length=255)),
                ('coursesubject', models.CharField(max_length=255)),
                ('coursenum', models.IntegerField()),
                ('sectionnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.IntegerField(unique=True)),
                ('roomnumber', models.IntegerField()),
                ('building', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.IntegerField(unique=True)),
                ('topic', models.CharField(max_length=255)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginpage.Course')),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginpage.Room')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('online', models.BooleanField()),
                ('usertype', models.CharField(max_length=255)),
                ('sessionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginpage.Session')),
            ],
        ),
    ]
